### ISSUE TITLE
Persistent unchecked "Watched" box on Class 1 in Classes tab

### ISSUE THREAD

**Issue by Gorvelt** [labrocadabro/communitytaught#14] opened 2023-02-07 09:55 UTC
For some reason the "Watched" box stays unchecked after refreshing the page. So far only this class is affected.

Browser: Mozilla Firefox (v109.0.1)

**Comment by labrocadabro** [comment] 2023-02-07 10:03
Someone else mentioned a similar issue with a different class. Unfortunately it's an intermittent problem and seems to be affecting only certain people. I haven't yet been able to reproduce it. If you could let me know your email address (feel free to email me at laura@abrocadabro.com if you'd rather not post it here), I can take a look at your account and see if that gives me any clues.

**Comment by Gorvelt** [comment] 2023-02-07 19:21
Hey! My email is ***@***.*** Best of luck!

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by labrocadabro** [comment] 2023-02-08 00:53
Unfortunately, your email address didn't make it through.

**Comment by labrocadabro** [comment] 2023-02-08 11:51
Ok so I took a look and for some as-yet unidentified reason, two entries were saved for your class 1 lesson progress. That's not supposed to happen, and it seems that the duplicate entry was causing issues with the logic for updating progress. As a fix to your specific issue, I've deleted the second entry and updated the watch status to true. Please do let me know if you experience this again.

I'm keeping this issue open as I still need to identify and fix the root cause.

**Comment by Gorvelt** [comment] 2023-02-08 11:57
Thanks a lot! Class 7 seems to be having the same problem as well. Do you want me to include my sequence of actions in the future when it happens again?

**Comment by Gorvelt** [comment] 2023-02-08 13:22
Checked it and there are no problems :D

**Comment by labrocadabro** [comment] 2023-12-29 20:36
Haven't had any further reports of this, so I'm closing it.

**Closed by labrocadabro** 2023-12-29 20:36 UTC
